name: pipelines
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10.13
  - pip=24.0
  - pip:
    - pyspoa==0.2.1
    - matplotlib==3.8.3
    - parasail==1.3.4
    - pysam==0.22.0
    - biopython==1.83
